-- MySQL Script generated by MySQL Workbench
-- 2016年05月02日 星期一 22时46分45秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mail
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mail
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mail` DEFAULT CHARACTER SET utf8 ;
USE `mail` ;

-- -----------------------------------------------------
-- Table `mail`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mail`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(32) NULL,
  `passwordhash` VARCHAR(128) NULL,
  `nickname` VARCHAR(32) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_UNIQUE` (`account` ASC),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mail`.`mailaddresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mail`.`mailaddresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `account` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`userid` ASC),
  CONSTRAINT `usermailaddress`
    FOREIGN KEY (`userid`)
    REFERENCES `mail`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mail`.`mails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mail`.`mails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mailaddressid` INT NOT NULL,
  `subject` MEDIUMTEXT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `sender` VARCHAR(128) NOT NULL,
  `recver` MEDIUMTEXT NOT NULL,
  `sendtime` DATETIME,
  `recvtime` DATETIME,
  `type` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `mailaddress_idx` (`mailaddressid` ASC),
  CONSTRAINT `mailaddressmail`
    FOREIGN KEY (`mailaddressid`)
    REFERENCES `mail`.`mailaddresses` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mail`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mail`.`contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `nickname` VARCHAR(32) NOT NULL,
  `mailaddress` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_idx` (`userid` ASC),
  CONSTRAINT `user`
    FOREIGN KEY (`userid`)
    REFERENCES `mail`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mail`.`hostinfos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mail`.`hostinfos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `suffix` VARCHAR(128) NOT NULL,
  `smtphost` VARCHAR(128) NOT NULL,
  `smtpport` INT NOT NULL,
  `pop3host` VARCHAR(128) NOT NULL,
  `pop3port` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
